name: Generate TOC
on:
  push:
    branches: [ "main" ]  # 触发分支（根据你的主分支名称修改）
    paths: [ "README.md" ]  # 仅当 README.md 变更时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  generate-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate TOC
        uses: technote-space/toc-generator@v4  # 使用 TOC 生成工具
        with:
          filename: "README.md"  # 目标文件
          header: "## 📚 Content"   # 自定义目录标题（可选）
          footer: ""            # 目录底部注释（可选）

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "docs: Update TOC [skip ci]" || echo "No changes to commit"
          git push